name: Stable Build 🌙

on:
  release:
    types: [published]

jobs:
  deploy_to_itch:
    name: Deploy to Itch.io 🚀
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: build

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          sudo mv butler /usr/bin/butler

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push build MacMat01/strategic-fruits:stable
